In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#importar o arquivo com os acessos por mês de fev/2009 a 2018 em um dataframe
df_fev2009_2018 = pd.read_csv('./data/Acessos_Telefonia_Movel_200902-2018_Modalidade_Colunas.csv', sep=';')

In [3]:
#importar o arquivo com os acessos por mês de 2005 a jan/2009 em um dataframe
df_2005_jan2009 = pd.read_csv('./data/Acessos_Telefonia_Movel_2005-200901_Modalidade_Colunas.csv', sep=';')

In [4]:
#verificar a coluna de jan/2009 para transpor para uma planilha conjunta (contendo todos os meses de 2009)
df_2005_jan2009.head(10)

,CNPJ,Código Nacional,Modalidade de Cobrança,Empresa,Porte da Prestadora,Grupo Econômico,2005-02,2005-03,2005-04,2005-05,...,2008-04,2008-05,2008-06,2008-07,2008-08,2008-09,2008-10,2008-11,2008-12,2009-01
0,40432544000147,11,Pós-pago,CLARO,Grande Porte,TELECOM AMERICAS,645139.0,657803.0,673296.0,673213.0,...,1481520.0,1556478.0,1605889.0,1643963.0,1715614.0,1781784.0,1850851.0,1888824.0,1946079,1979850
1,40432544000147,11,Pré-pago,CLARO,Grande Porte,TELECOM AMERICAS,1863716.0,1880595.0,1955845.0,2085892.0,...,3717444.0,3777347.0,3853205.0,3894946.0,3988094.0,4084199.0,4159504.0,4210726.0,4315267,4314945
2,40432544000147,12,Pós-pago,CLARO,Grande Porte,TELECOM AMERICAS,34337.0,35413.0,36311.0,36965.0,...,82178.0,83327.0,84418.0,86004.0,89260.0,91805.0,94713.0,96238.0,100040,101486
3,40432544000147,12,Pré-pago,CLARO,Grande Porte,TELECOM AMERICAS,256139.0,261462.0,272160.0,284615.0,...,491787.0,500011.0,507335.0,515668.0,527923.0,540264.0,553209.0,564694.0,585808,590899
4,40432544000147,13,Pós-pago,CLARO,Grande Porte,TELECOM AMERICAS,27587.0,28866.0,30108.0,29904.0,...,101403.0,102911.0,104829.0,110927.0,115609.0,118693.0,123930.0,125710.0,128074,128679
5,40432544000147,13,Pré-pago,CLARO,Grande Porte,TELECOM AMERICAS,265481.0,266587.0,274460.0,284068.0,...,382044.0,384873.0,389882.0,394280.0,400269.0,408410.0,417509.0,413642.0,425771,428266
6,40432544000147,14,Pós-pago,CLARO,Grande Porte,TELECOM AMERICAS,10204.0,11211.0,12239.0,12705.0,...,50184.0,51067.0,51382.0,66483.0,67858.0,69232.0,72279.0,73971.0,77355,79307
7,40432544000147,14,Pré-pago,CLARO,Grande Porte,TELECOM AMERICAS,82309.0,85903.0,93078.0,104164.0,...,274203.0,278855.0,284881.0,290242.0,297822.0,305361.0,314081.0,325698.0,339087,340823
8,40432544000147,15,Pós-pago,CLARO,Grande Porte,TELECOM AMERICAS,15232.0,16254.0,17012.0,17514.0,...,41420.0,43128.0,50289.0,66100.0,67800.0,69500.0,72029.0,87938.0,90582,91803
9,40432544000147,15,Pré-pago,CLARO,Grande Porte,TELECOM AMERICAS,107678.0,109780.0,115613.0,123723.0,...,262067.0,266394.0,274146.0,277390.0,281863.0,290787.0,297595.0,306036.0,317501,319991

In [5]:
df_2005_jan2009.shape

(551, 54)

In [6]:
df_fev2009_2018 .shape

(906, 126)

In [7]:
#construir uma planilha só com todos os meses de 2009, pegando apenas jan/2009 da planilha df_2005_jan2009
df_2009_2018 = pd.merge(df_fev2009_2018, df_2005_jan2009[['CNPJ', 'Código Nacional', 'Modalidade de Cobrança', 'Empresa',
       'Porte da Prestadora', 'Grupo Econômico', '2009-01']], how='outer')

In [8]:
#organizar as colunas de modo crescente, uma vez que 2009-01 foi para o final da planilha pós-merge
df_2009_2018 = df_2009_2018[['CNPJ', 'Código Nacional', 'UF', 'Modalidade de Cobrança',
       'Empresa', 'Porte da Prestadora', 'Grupo Econômico', '2009-01', '2009-02',
       '2009-03', '2009-04', '2009-05', '2009-06', '2009-07', '2009-08',
       '2009-09', '2009-10', '2009-11', '2009-12', '2010-01', '2010-02',
       '2010-03', '2010-04', '2010-05', '2010-06', '2010-07', '2010-08',
       '2010-09', '2010-10', '2010-11', '2010-12', '2011-01', '2011-02',
       '2011-03', '2011-04', '2011-05', '2011-06', '2011-07', '2011-08',
       '2011-09', '2011-10', '2011-11', '2011-12', '2012-01', '2012-02',
       '2012-03', '2012-04', '2012-05', '2012-06', '2012-07', '2012-08',
       '2012-09', '2012-10', '2012-11', '2012-12', '2013-01', '2013-02',
       '2013-03', '2013-04', '2013-05', '2013-06', '2013-07', '2013-08',
       '2013-09', '2013-10', '2013-11', '2013-12', '2014-01', '2014-02',
       '2014-03', '2014-04', '2014-05', '2014-06', '2014-07', '2014-08',
       '2014-09', '2014-10', '2014-11', '2014-12', '2015-01', '2015-02',
       '2015-03', '2015-04', '2015-05', '2015-06', '2015-07', '2015-08',
       '2015-09', '2015-10', '2015-11', '2015-12', '2016-01', '2016-02',
       '2016-03', '2016-04', '2016-05', '2016-06', '2016-07', '2016-08',
       '2016-09', '2016-10', '2016-11', '2016-12', '2017-01', '2017-02',
       '2017-03', '2017-04', '2017-05', '2017-06', '2017-07', '2017-08',
       '2017-09', '2017-10', '2017-11', '2017-12', '2018-01', '2018-02',
       '2018-03', '2018-04', '2018-05', '2018-06', '2018-07', '2018-08',
       '2018-09', '2018-10', '2018-11', '2018-12']]

In [9]:
#verificar se tudo está correto
df_2009_2018.head()

,CNPJ,Código Nacional,UF,Modalidade de Cobrança,Empresa,Porte da Prestadora,Grupo Econômico,2009-01,2009-02,2009-03,...,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12
0,40432544000147,11,SP,Pós-pago,CLARO,Grande Porte,TELECOM AMERICAS,1979850.0,2010944.0,2017485.0,...,4600142.0,4719410.0,4789826.0,4777660.0,4750476.0,4743785.0,4659019.0,4695930.0,4775796.0,4782195.0
1,40432544000147,11,SP,Pré-pago,CLARO,Grande Porte,TELECOM AMERICAS,4314945.0,4311897.0,4307952.0,...,2795051.0,2732371.0,2694531.0,2657010.0,2629856.0,2583029.0,2613233.0,2536107.0,2462704.0,2313555.0
2,40432544000147,12,SP,Pós-pago,CLARO,Grande Porte,TELECOM AMERICAS,101486.0,102574.0,104066.0,...,271619.0,274336.0,273992.0,274899.0,273201.0,269960.0,271421.0,272565.0,275922.0,277880.0
3,40432544000147,12,SP,Pré-pago,CLARO,Grande Porte,TELECOM AMERICAS,590899.0,592495.0,593294.0,...,430269.0,430144.0,433791.0,432342.0,433479.0,427796.0,434129.0,419556.0,404018.0,387164.0
4,40432544000147,13,SP,Pós-pago,CLARO,Grande Porte,TELECOM AMERICAS,128679.0,129018.0,128502.0,...,205669.0,206654.0,207410.0,207730.0,207203.0,206072.0,206963.0,207857.0,209689.0,224933.0

In [10]:
#criar dataframe para cada ano
df_2009 = df_2009_2018[['CNPJ', 'Código Nacional', 'UF', 'Modalidade de Cobrança',
       'Empresa', 'Porte da Prestadora', 'Grupo Econômico', '2009-01', '2009-02',
       '2009-03', '2009-04', '2009-05', '2009-06', '2009-07', '2009-08',
       '2009-09', '2009-10', '2009-11', '2009-12']]
df_2010 = df_2009_2018[['CNPJ', 'Código Nacional', 'UF', 'Modalidade de Cobrança',
       'Empresa', 'Porte da Prestadora', 'Grupo Econômico', '2010-01', '2010-02',
       '2010-03', '2010-04', '2010-05', '2010-06', '2010-07', '2010-08',
       '2010-09', '2010-10', '2010-11', '2010-12']]
df_2011 = df_2009_2018[['CNPJ', 'Código Nacional', 'UF', 'Modalidade de Cobrança',
       'Empresa', 'Porte da Prestadora', 'Grupo Econômico', '2011-01', '2011-02',
       '2011-03', '2011-04', '2011-05', '2011-06', '2011-07', '2011-08',
       '2011-09', '2011-10', '2011-11', '2011-12']]
df_2012 = df_2009_2018[['CNPJ', 'Código Nacional', 'UF', 'Modalidade de Cobrança',
       'Empresa', 'Porte da Prestadora', 'Grupo Econômico', '2012-01', '2012-02',
       '2012-03', '2012-04', '2012-05', '2012-06', '2012-07', '2012-08',
       '2012-09', '2012-10', '2012-11', '2012-12']]
df_2013 = df_2009_2018[['CNPJ', 'Código Nacional', 'UF', 'Modalidade de Cobrança',
       'Empresa', 'Porte da Prestadora', 'Grupo Econômico', '2013-01', '2013-02',
       '2013-03', '2013-04', '2013-05', '2013-06', '2013-07', '2013-08',
       '2013-09', '2013-10', '2013-11', '2013-12']]
df_2014 = df_2009_2018[['CNPJ', 'Código Nacional', 'UF', 'Modalidade de Cobrança',
       'Empresa', 'Porte da Prestadora', 'Grupo Econômico', '2014-01', '2014-02',
       '2014-03', '2014-04', '2014-05', '2014-06', '2014-07', '2014-08',
       '2014-09', '2014-10', '2014-11', '2014-12']]
df_2015 = df_2009_2018[['CNPJ', 'Código Nacional', 'UF', 'Modalidade de Cobrança',
       'Empresa', 'Porte da Prestadora', 'Grupo Econômico', '2015-01', '2015-02',
       '2015-03', '2015-04', '2015-05', '2015-06', '2015-07', '2015-08',
       '2015-09', '2015-10', '2015-11', '2015-12']]
df_2016 = df_2009_2018[['CNPJ', 'Código Nacional', 'UF', 'Modalidade de Cobrança',
       'Empresa', 'Porte da Prestadora', 'Grupo Econômico', '2016-01', '2016-02',
       '2016-03', '2016-04', '2016-05', '2016-06', '2016-07', '2016-08',
       '2016-09', '2016-10', '2016-11', '2016-12']]
df_2017 = df_2009_2018[['CNPJ', 'Código Nacional', 'UF', 'Modalidade de Cobrança',
       'Empresa', 'Porte da Prestadora', 'Grupo Econômico', '2017-01', '2017-02',
       '2017-03', '2017-04', '2017-05', '2017-06', '2017-07', '2017-08',
       '2017-09', '2017-10', '2017-11', '2017-12']]
df_2018 = df_2009_2018[['CNPJ', 'Código Nacional', 'UF', 'Modalidade de Cobrança',
       'Empresa', 'Porte da Prestadora', 'Grupo Econômico', '2018-01', '2018-02',
       '2018-03', '2018-04', '2018-05', '2018-06', '2018-07', '2018-08',
       '2018-09', '2018-10', '2018-11', '2018-12']]

In [11]:
#criar lista dos dfs para posterior iteração
lista_dfs = [df_2009, df_2010, df_2011, df_2012, df_2013, df_2014, df_2015, df_2016, df_2017, df_2018]

In [12]:
#criar uma variável com a quantidade de células no dataframe - todos os dataframes têm o mesmo tamanho, conforme checagem utilizando df.shape
quant_células_valor = 19 * 906

In [13]:
#criar uma função para checar a quantidade de NaN presentes nos dataframes
def check_nas(lista_df):
    lista_nas = []
    for df in lista_df:
        valor_na = df.isna().sum().sum()
        lista_nas.append(valor_na)
    lista_qnt_x_total = []
    for qnt_na in lista_nas:
        qnt_x_total = round((qnt_na * 100) / quant_células_valor, 2)
        lista_qnt_x_total.append(qnt_x_total)
    return lista_qnt_x_total

In [14]:
#usar a função check_nas para verificar a porcentagem de NaN dentro de cada dataframe
check_nas(lista_dfs)

[24.65, 24.64, 24.69, 24.61, 22.78, 21.01, 18.8, 17.92, 17.07, 13.93]

In [15]:
#preencher os NaN com 0, conforme decisão metodológica
df_2009 = df_2009.fillna(0)
df_2010 = df_2010.fillna(0)
df_2011 = df_2011.fillna(0)
df_2012 = df_2012.fillna(0)
df_2013 = df_2013.fillna(0)
df_2014 = df_2014.fillna(0)
df_2015 = df_2015.fillna(0)
df_2016 = df_2016.fillna(0)
df_2017 = df_2017.fillna(0)
df_2018 = df_2018.fillna(0)

In [16]:
#adicionar a coluna de media_ano em todos os dataframes
df_2009['media_ano'] = round(df_2009[['2009-01', '2009-02',
       '2009-03', '2009-04', '2009-05', '2009-06', '2009-07', '2009-08',
       '2009-09', '2009-10', '2009-11', '2009-12']].mean(axis=1), 2)
df_2010['media_ano'] = round(df_2010[['2010-01', '2010-02',
       '2010-03', '2010-04', '2010-05', '2010-06', '2010-07', '2010-08',
       '2010-09', '2010-10', '2010-11', '2010-12']].mean(axis=1), 2)
df_2011['media_ano'] = round(df_2011[['2011-01', '2011-02',
       '2011-03', '2011-04', '2011-05', '2011-06', '2011-07', '2011-08',
       '2011-09', '2011-10', '2011-11', '2011-12']].mean(axis=1), 2)
df_2012['media_ano'] = round(df_2012[['2012-01', '2012-02',
       '2012-03', '2012-04', '2012-05', '2012-06', '2012-07', '2012-08',
       '2012-09', '2012-10', '2012-11', '2012-12']].mean(axis=1), 2)
df_2013['media_ano'] = round(df_2013[['2013-01', '2013-02',
       '2013-03', '2013-04', '2013-05', '2013-06', '2013-07', '2013-08',
       '2013-09', '2013-10', '2013-11', '2013-12']].mean(axis=1), 2)
df_2014['media_ano'] = round(df_2014[['2014-01', '2014-02',
       '2014-03', '2014-04', '2014-05', '2014-06', '2014-07', '2014-08',
       '2014-09', '2014-10', '2014-11', '2014-12']].mean(axis=1), 2)
df_2015['media_ano'] = round(df_2015[['2015-01', '2015-02',
       '2015-03', '2015-04', '2015-05', '2015-06', '2015-07', '2015-08',
       '2015-09', '2015-10', '2015-11', '2015-12']].mean(axis=1), 2)
df_2016['media_ano'] = round(df_2016[['2016-01', '2016-02',
       '2016-03', '2016-04', '2016-05', '2016-06', '2016-07', '2016-08',
       '2016-09', '2016-10', '2016-11', '2016-12']].mean(axis=1), 2)
df_2017['media_ano'] = round(df_2017[['2017-01', '2017-02',
       '2017-03', '2017-04', '2017-05', '2017-06', '2017-07', '2017-08',
       '2017-09', '2017-10', '2017-11', '2017-12']].mean(axis=1), 2)
df_2018['media_ano'] = round(df_2018[['2018-01', '2018-02',
       '2018-03', '2018-04', '2018-05', '2018-06', '2018-07', '2018-08',
       '2018-09', '2018-10', '2018-11', '2018-12']].mean(axis=1), 2)

In [17]:
#utilizar o value_counts() para certificar se não há nomes duplicados por erro de entrada de dados nas variáveis que serão utilizadas no cálculo de parcela de mercado: grupo econômico, UF, Código Nacional
df_2018['Grupo Econômico'].value_counts()

Grupo Econômico
TELECOM ITALIA                  272
TELECOM AMERICAS                136
TELEFÔNICA                      134
OI                              134
NEXTEL                          102
OUTROS                           69
0                                14
ALGAR (CTBC TELECOM)             14
DATORA                           13
PORTO SEGURO                     13
PREFEITURA DE LONDRINA/COPEL      4
UNICEL                            1
Name: count, dtype: int64

In [18]:
#criar dataframes por UF e Grupo Econômico, somando a coluna media_ano, depois criar uma coluna chamada market_share com o cálculo da parcela de mercado por UF
#o cálculo de market_share pegou a media_ano e dividiu pela media_ano do df agrupado por UF
df_2009_uf = pd.DataFrame(df_2009.groupby(['UF', 'Grupo Econômico'])['media_ano'].sum())
df_2009_uf['market_share'] = round(((df_2009_uf['media_ano'] / df_2009_uf.groupby('UF')['media_ano'].sum())), 4)

df_2010_uf = pd.DataFrame(df_2010.groupby(['UF', 'Grupo Econômico'])['media_ano'].sum())
df_2010_uf['market_share'] = round(((df_2010_uf['media_ano'] / df_2010_uf.groupby('UF')['media_ano'].sum())), 4)

df_2011_uf = pd.DataFrame(df_2011.groupby(['UF', 'Grupo Econômico'])['media_ano'].sum())
df_2011_uf['market_share'] = round(((df_2011_uf['media_ano'] / df_2011_uf.groupby('UF')['media_ano'].sum())), 4)

df_2012_uf = pd.DataFrame(df_2012.groupby(['UF', 'Grupo Econômico'])['media_ano'].sum())
df_2012_uf['market_share'] = round(((df_2012_uf['media_ano'] / df_2012_uf.groupby('UF')['media_ano'].sum())), 4)

df_2013_uf = pd.DataFrame(df_2013.groupby(['UF', 'Grupo Econômico'])['media_ano'].sum())
df_2013_uf['market_share'] = round(((df_2013_uf['media_ano'] / df_2013_uf.groupby('UF')['media_ano'].sum())), 4)

df_2014_uf = pd.DataFrame(df_2014.groupby(['UF', 'Grupo Econômico'])['media_ano'].sum())
df_2014_uf['market_share'] = round(((df_2014_uf['media_ano'] / df_2014_uf.groupby('UF')['media_ano'].sum())), 4)

df_2015_uf = pd.DataFrame(df_2015.groupby(['UF', 'Grupo Econômico'])['media_ano'].sum())
df_2015_uf['market_share'] = round(((df_2015_uf['media_ano'] / df_2015_uf.groupby('UF')['media_ano'].sum())), 4)

df_2016_uf = pd.DataFrame(df_2016.groupby(['UF', 'Grupo Econômico'])['media_ano'].sum())
df_2016_uf['market_share'] = round(((df_2016_uf['media_ano'] / df_2016_uf.groupby('UF')['media_ano'].sum())), 4)

df_2017_uf = pd.DataFrame(df_2017.groupby(['UF', 'Grupo Econômico'])['media_ano'].sum())
df_2017_uf['market_share'] = round(((df_2017_uf['media_ano'] / df_2017_uf.groupby('UF')['media_ano'].sum())), 4)

df_2018_uf = pd.DataFrame(df_2018.groupby(['UF', 'Grupo Econômico'])['media_ano'].sum())
df_2018_uf['market_share'] = round(((df_2018_uf['media_ano'] / df_2018_uf.groupby('UF')['media_ano'].sum())), 4)

In [19]:
#fazer um recorte para verificar os valores de market_share
df_2009_uf.loc[['DF', 'PI']]

                      media_ano  market_share
UF Grupo Econômico
DF NEXTEL                  0.00        0.0000
   OI                1035941.59        0.2670
   OUTROS                  0.00        0.0000
   TELECOM AMERICAS  1199497.50        0.3091
   TELECOM ITALIA     645866.16        0.1664
   TELEFÔNICA         998998.75        0.2575
PI NEXTEL                  0.00        0.0000
   OI                 477416.67        0.2922
   OUTROS                  0.00        0.0000
   TELECOM AMERICAS   543904.33        0.3329
   TELECOM ITALIA     571422.00        0.3498
   TELEFÔNICA          41050.42        0.0251

In [20]:
#criar dataframes por DDD (Código Nacional) e Grupo Econômico, somando a coluna media_ano, depois criar uma coluna chamada market_share com o cálculo da parcela de mercado por DDD
#o cálculo de market_share pegou a media_ano e dividiu pela media_ano do df agrupado por DDD
df_2009_ddd = pd.DataFrame(df_2009.groupby(['Código Nacional', 'Grupo Econômico'])['media_ano'].sum())
df_2009_ddd['market_share'] = round(((df_2009_ddd['media_ano'] / df_2009_ddd.groupby('Código Nacional')['media_ano'].sum())), 4)

df_2010_ddd = pd.DataFrame(df_2010.groupby(['Código Nacional', 'Grupo Econômico'])['media_ano'].sum())
df_2010_ddd['market_share'] = round(((df_2010_ddd['media_ano'] / df_2010_ddd.groupby('Código Nacional')['media_ano'].sum())), 4)

df_2011_ddd = pd.DataFrame(df_2011.groupby(['Código Nacional', 'Grupo Econômico'])['media_ano'].sum())
df_2011_ddd['market_share'] = round(((df_2011_ddd['media_ano'] / df_2011_ddd.groupby('Código Nacional')['media_ano'].sum())), 4)

df_2012_ddd = pd.DataFrame(df_2012.groupby(['Código Nacional', 'Grupo Econômico'])['media_ano'].sum())
df_2012_ddd['market_share'] = round(((df_2012_ddd['media_ano'] / df_2012_ddd.groupby('Código Nacional')['media_ano'].sum())), 4)

df_2013_ddd = pd.DataFrame(df_2013.groupby(['Código Nacional', 'Grupo Econômico'])['media_ano'].sum())
df_2013_ddd['market_share'] = round(((df_2013_ddd['media_ano'] / df_2013_ddd.groupby('Código Nacional')['media_ano'].sum())), 4)

df_2014_ddd = pd.DataFrame(df_2014.groupby(['Código Nacional', 'Grupo Econômico'])['media_ano'].sum())
df_2014_ddd['market_share'] = round(((df_2014_ddd['media_ano'] / df_2014_ddd.groupby('Código Nacional')['media_ano'].sum())), 4)

df_2015_ddd = pd.DataFrame(df_2015.groupby(['Código Nacional', 'Grupo Econômico'])['media_ano'].sum())
df_2015_ddd['market_share'] = round(((df_2015_ddd['media_ano'] / df_2015_ddd.groupby('Código Nacional')['media_ano'].sum())), 4)

df_2016_ddd = pd.DataFrame(df_2016.groupby(['Código Nacional', 'Grupo Econômico'])['media_ano'].sum())
df_2016_ddd['market_share'] = round(((df_2016_ddd['media_ano'] / df_2016_ddd.groupby('Código Nacional')['media_ano'].sum())), 4)

df_2017_ddd = pd.DataFrame(df_2017.groupby(['Código Nacional', 'Grupo Econômico'])['media_ano'].sum())
df_2017_ddd['market_share'] = round(((df_2017_ddd['media_ano'] / df_2017_ddd.groupby('Código Nacional')['media_ano'].sum())), 4)

df_2018_ddd = pd.DataFrame(df_2018.groupby(['Código Nacional', 'Grupo Econômico'])['media_ano'].sum())
df_2018_ddd['market_share'] = round(((df_2018_ddd['media_ano'] / df_2018_ddd.groupby('Código Nacional')['media_ano'].sum())), 4)

In [21]:
#fazer um recorte para verificar os valores de market_share
df_2009_ddd.loc[[61, 86]]

                                   media_ano  market_share
Código Nacional Grupo Econômico
61              NEXTEL                  0.00        0.0000
                OI                1035941.59        0.2404
                OUTROS                  0.00        0.0000
                TELECOM AMERICAS  1546783.25        0.3589
                TELECOM ITALIA     727524.66        0.1688
                TELEFÔNICA         998998.75        0.2318
86              NEXTEL                  0.00        0.0000
                OI                 445894.00        0.3285
                OUTROS                  0.00        0.0000
                TELECOM AMERICAS   442945.58        0.3263
                TELECOM ITALIA     436238.25        0.3214
                TELEFÔNICA          32321.42        0.0238

In [22]:
#criar uma função para verificar a concentração de mercado a partir do HHI
def analise_hhi(valor_hhi):
    if valor_hhi <= 1500:
        return "pouco concentrado"
    if valor_hhi > 1500 and valor_hhi <= 2500:
        return "moderado"
    else:
        return "altamente concentrado"

In [25]:
#para o cálculo do HHI por UF, primeiro criamos uma coluna chamada hhi_empresa pegando o valor do market_share de cada empresa e elevando o número ao quadrado
df_2009_uf['hhi_empresa'] = (df_2009_uf['market_share'] ** 2) * 10000

df_2010_uf['hhi_empresa'] = (df_2010_uf['market_share'] ** 2) * 10000

df_2011_uf['hhi_empresa'] = (df_2011_uf['market_share'] ** 2) * 10000

df_2012_uf['hhi_empresa'] = (df_2012_uf['market_share'] ** 2) * 10000

df_2013_uf['hhi_empresa'] = (df_2013_uf['market_share'] ** 2) * 10000

df_2014_uf['hhi_empresa'] = (df_2014_uf['market_share'] ** 2) * 10000

df_2015_uf['hhi_empresa'] = (df_2015_uf['market_share'] ** 2) * 10000

df_2016_uf['hhi_empresa'] = (df_2016_uf['market_share'] ** 2) * 10000

df_2017_uf['hhi_empresa'] = (df_2017_uf['market_share'] ** 2) * 10000

df_2018_uf['hhi_empresa'] = (df_2018_uf['market_share'] ** 2) * 10000

In [26]:
df_2014_uf

                     media_ano  market_share  hhi_empresa
UF Grupo Econômico
AC NEXTEL                 1.00        0.0000       0.0000
   OI                 71635.58        0.0792      62.7264
   OUTROS                 0.00        0.0000       0.0000
   TELECOM AMERICAS  198745.58        0.2196     482.2416
   TELECOM ITALIA     55493.91        0.0613      37.5769
...                        ...           ...          ...
TO OI                608383.25        0.3089     954.1921
   OUTROS                 0.00        0.0000       0.0000
   TELECOM AMERICAS  700638.75        0.3558    1265.9364
   TELECOM ITALIA    275343.00        0.1398     195.4404
   TELEFÔNICA        385036.08        0.1955     382.2025

[179 rows x 3 columns]

In [27]:
#a partir da coluna de hhi_empresa, somamos os valores, criando um novo dataframe com uma coluna contendo o cálculo de HHI por UF
df_2009_hhi_uf = df_2009_uf.groupby('UF')['hhi_empresa'].sum()
df_2009_hhi_uf = pd.DataFrame(df_2009_hhi_uf).reset_index()
df_2009_hhi_uf.columns = ['UF', 'HHI']

df_2010_hhi_uf = df_2010_uf.groupby('UF')['hhi_empresa'].sum()
df_2010_hhi_uf = pd.DataFrame(df_2010_hhi_uf).reset_index()
df_2010_hhi_uf.columns = ['UF', 'HHI']

df_2011_hhi_uf = df_2011_uf.groupby('UF')['hhi_empresa'].sum()
df_2011_hhi_uf = pd.DataFrame(df_2011_hhi_uf).reset_index()
df_2011_hhi_uf.columns = ['UF', 'HHI']

df_2012_hhi_uf = df_2012_uf.groupby('UF')['hhi_empresa'].sum()
df_2012_hhi_uf = pd.DataFrame(df_2012_hhi_uf).reset_index()
df_2012_hhi_uf.columns = ['UF', 'HHI']

df_2013_hhi_uf = df_2013_uf.groupby('UF')['hhi_empresa'].sum()
df_2013_hhi_uf = pd.DataFrame(df_2013_hhi_uf).reset_index()
df_2013_hhi_uf.columns = ['UF', 'HHI']

df_2014_hhi_uf = df_2014_uf.groupby('UF')['hhi_empresa'].sum()
df_2014_hhi_uf = pd.DataFrame(df_2014_hhi_uf).reset_index()
df_2014_hhi_uf.columns = ['UF', 'HHI']

df_2015_hhi_uf = df_2015_uf.groupby('UF')['hhi_empresa'].sum()
df_2015_hhi_uf = pd.DataFrame(df_2015_hhi_uf).reset_index()
df_2015_hhi_uf.columns = ['UF', 'HHI']

df_2016_hhi_uf = df_2016_uf.groupby('UF')['hhi_empresa'].sum()
df_2016_hhi_uf = pd.DataFrame(df_2016_hhi_uf).reset_index()
df_2016_hhi_uf.columns = ['UF', 'HHI']

df_2017_hhi_uf = df_2017_uf.groupby('UF')['hhi_empresa'].sum()
df_2017_hhi_uf = pd.DataFrame(df_2017_hhi_uf).reset_index()
df_2017_hhi_uf.columns = ['UF', 'HHI']

df_2018_hhi_uf = df_2018_uf.groupby('UF')['hhi_empresa'].sum()
df_2018_hhi_uf = pd.DataFrame(df_2018_hhi_uf).reset_index()
df_2018_hhi_uf.columns = ['UF', 'HHI']

In [28]:
#aplicar a função analise_hhi no dataframe, criando uma coluna analise_mercado_hhi
df_2009_hhi_uf['analise_mercado_hhi'] = df_2009_hhi_uf['HHI'].apply(analise_hhi)

df_2010_hhi_uf['analise_mercado_hhi'] = df_2010_hhi_uf['HHI'].apply(analise_hhi)

df_2011_hhi_uf['analise_mercado_hhi'] = df_2011_hhi_uf['HHI'].apply(analise_hhi)

df_2012_hhi_uf['analise_mercado_hhi'] = df_2012_hhi_uf['HHI'].apply(analise_hhi)

df_2013_hhi_uf['analise_mercado_hhi'] = df_2013_hhi_uf['HHI'].apply(analise_hhi)

df_2014_hhi_uf['analise_mercado_hhi'] = df_2014_hhi_uf['HHI'].apply(analise_hhi)

df_2015_hhi_uf['analise_mercado_hhi'] = df_2015_hhi_uf['HHI'].apply(analise_hhi)

df_2016_hhi_uf['analise_mercado_hhi'] = df_2016_hhi_uf['HHI'].apply(analise_hhi)

df_2017_hhi_uf['analise_mercado_hhi'] = df_2017_hhi_uf['HHI'].apply(analise_hhi)

df_2018_hhi_uf['analise_mercado_hhi'] = df_2018_hhi_uf['HHI'].apply(analise_hhi)

In [38]:
#verificar se a função de análise de HHI e a coluna estão corretas
df_2016_hhi_uf.nlargest(5, 'HHI')

    UF        HHI    analise_mercado_hhi
7   ES  6359.6530  altamente concentrado
0   AC  5051.4162  altamente concentrado
2   AM  4717.4967  altamente concentrado
21  RR  4673.9886  altamente concentrado
3   AP  4325.4864  altamente concentrado

In [35]:
#para o cálculo do HHI por DDD, primeiro criamos uma coluna chamada hhi_empresa pegando o valor do market_share de cada DDD e elevando o número ao quadrado
df_2009_ddd['hhi_empresa'] = (df_2009_ddd['market_share'] ** 2) * 10000

df_2010_ddd['hhi_empresa'] = (df_2010_ddd['market_share'] ** 2) * 10000

df_2011_ddd['hhi_empresa'] = (df_2011_ddd['market_share'] ** 2) * 10000

df_2012_ddd['hhi_empresa'] = (df_2012_ddd['market_share'] ** 2) * 10000

df_2013_ddd['hhi_empresa'] = (df_2013_ddd['market_share'] ** 2) * 10000

df_2014_ddd['hhi_empresa'] = (df_2014_ddd['market_share'] ** 2) * 10000

df_2015_ddd['hhi_empresa'] = (df_2015_ddd['market_share'] ** 2) * 10000

df_2016_ddd['hhi_empresa'] = (df_2016_ddd['market_share'] ** 2) * 10000

df_2017_ddd['hhi_empresa'] = (df_2017_ddd['market_share'] ** 2) * 10000

df_2018_ddd['hhi_empresa'] = (df_2018_ddd['market_share'] ** 2) * 10000

In [36]:
#a partir da coluna de hhi_empresa - agora por DDD -, somamos os valores, criamos um novo dataframe com uma coluna contendo o cálculo de HHI por DDD: somamo
df_2009_hhi_ddd = df_2009_ddd.groupby('Código Nacional')['hhi_empresa'].sum()
df_2009_hhi_ddd = pd.DataFrame(df_2009_hhi_ddd).reset_index()
df_2009_hhi_ddd.columns = ['Código Nacional', 'HHI']

df_2010_hhi_ddd = df_2010_ddd.groupby('Código Nacional')['hhi_empresa'].sum()
df_2010_hhi_ddd = pd.DataFrame(df_2010_hhi_ddd).reset_index()
df_2010_hhi_ddd.columns = ['Código Nacional', 'HHI']

df_2011_hhi_ddd = df_2011_ddd.groupby('Código Nacional')['hhi_empresa'].sum()
df_2011_hhi_ddd = pd.DataFrame(df_2011_hhi_ddd).reset_index()
df_2011_hhi_ddd.columns = ['Código Nacional', 'HHI']

df_2012_hhi_ddd = df_2012_ddd.groupby('Código Nacional')['hhi_empresa'].sum()
df_2012_hhi_ddd = pd.DataFrame(df_2012_hhi_ddd).reset_index()
df_2012_hhi_ddd.columns = ['Código Nacional', 'HHI']

df_2013_hhi_ddd = df_2013_ddd.groupby('Código Nacional')['hhi_empresa'].sum()
df_2013_hhi_ddd = pd.DataFrame(df_2013_hhi_ddd).reset_index()
df_2013_hhi_ddd.columns = ['Código Nacional', 'HHI']

df_2014_hhi_ddd = df_2014_ddd.groupby('Código Nacional')['hhi_empresa'].sum()
df_2014_hhi_ddd = pd.DataFrame(df_2014_hhi_ddd).reset_index()
df_2014_hhi_ddd.columns = ['Código Nacional', 'HHI']

df_2015_hhi_ddd = df_2015_ddd.groupby('Código Nacional')['hhi_empresa'].sum()
df_2015_hhi_ddd = pd.DataFrame(df_2015_hhi_ddd).reset_index()
df_2015_hhi_ddd.columns = ['Código Nacional', 'HHI']

df_2016_hhi_ddd = df_2016_ddd.groupby('Código Nacional')['hhi_empresa'].sum()
df_2016_hhi_ddd = pd.DataFrame(df_2016_hhi_ddd).reset_index()
df_2016_hhi_ddd.columns = ['Código Nacional', 'HHI']

df_2017_hhi_ddd = df_2017_ddd.groupby('Código Nacional')['hhi_empresa'].sum()
df_2017_hhi_ddd = pd.DataFrame(df_2017_hhi_ddd).reset_index()
df_2017_hhi_ddd.columns = ['Código Nacional', 'HHI']

df_2018_hhi_ddd = df_2018_ddd.groupby('Código Nacional')['hhi_empresa'].sum()
df_2018_hhi_ddd = pd.DataFrame(df_2018_hhi_ddd).reset_index()
df_2018_hhi_ddd.columns = ['Código Nacional', 'HHI']

In [37]:
#aplicar a função analise_hhi no dataframe por DDD, criando uma coluna analise_mercado_hhi
df_2009_hhi_ddd['analise_mercado_hhi'] = df_2009_hhi_ddd['HHI'].apply(analise_hhi)

df_2010_hhi_ddd['analise_mercado_hhi'] = df_2010_hhi_ddd['HHI'].apply(analise_hhi)

df_2011_hhi_ddd['analise_mercado_hhi'] = df_2011_hhi_ddd['HHI'].apply(analise_hhi)

df_2012_hhi_ddd['analise_mercado_hhi'] = df_2012_hhi_ddd['HHI'].apply(analise_hhi)

df_2013_hhi_ddd['analise_mercado_hhi'] = df_2013_hhi_ddd['HHI'].apply(analise_hhi)

df_2014_hhi_ddd['analise_mercado_hhi'] = df_2014_hhi_ddd['HHI'].apply(analise_hhi)

df_2015_hhi_ddd['analise_mercado_hhi'] = df_2015_hhi_ddd['HHI'].apply(analise_hhi)

df_2016_hhi_ddd['analise_mercado_hhi'] = df_2016_hhi_ddd['HHI'].apply(analise_hhi)

df_2017_hhi_ddd['analise_mercado_hhi'] = df_2017_hhi_ddd['HHI'].apply(analise_hhi)

df_2018_hhi_ddd['analise_mercado_hhi'] = df_2018_hhi_ddd['HHI'].apply(analise_hhi)

In [40]:
#verificar se a função de análise de HHI e a coluna estão corretas
df_2016_hhi_ddd.nlargest(5, 'HHI')

    Código Nacional        HHI    analise_mercado_hhi
13               28  7207.3182  altamente concentrado
12               27  6209.4996  altamente concentrado
60               93  5453.2180  altamente concentrado
25               45  5426.3866  altamente concentrado
41               68  5051.4162  altamente concentrado

In [41]:
#exportar como csv os dataframes com as análises de concentração de mercado
#análise de market share por UF - market share
#df_2009_uf.to_csv("cm_2009_uf.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2010_uf.to_csv("cm_2010_uf.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2011_uf.to_csv("cm_2011_uf.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2012_uf.to_csv("cm_2012_uf.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2013_uf.to_csv("cm_2013_uf.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2014_uf.to_csv("cm_2014_uf.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2015_uf.to_csv("cm_2015_uf.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2016_uf.to_csv("cm_2016_uf.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2017_uf.to_csv("cm_2017_uf.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2018_uf.to_csv("cm_2018_uf.csv", sep=';', decimal = ",", encoding='utf-8')

In [42]:
#exportar como csv os dataframes com as análises de concentração de mercado
#análise de market share por UF - HHI
#df_2009_hhi_uf.to_csv("hhi_2009_uf.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2010_hhi_uf.to_csv("hhi_2010_uf.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2011_hhi_uf.to_csv("hhi_2011_uf.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2012_hhi_uf.to_csv("hhi_2012_uf.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2013_hhi_uf.to_csv("hhi_2013_uf.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2014_hhi_uf.to_csv("hhi_2014_uf.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2015_hhi_uf.to_csv("hhi_2015_uf.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2016_hhi_uf.to_csv("hhi_2016_uf.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2017_hhi_uf.to_csv("hhi_2017_uf.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2018_hhi_uf.to_csv("hhi_2018_uf.csv", sep=';', decimal = ",", encoding='utf-8')

In [43]:
#exportar como csv os dataframes com as análises de concentração de mercado
#análise de market share por DDD
#df_2009_ddd.to_csv("cm_2009_ddd.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2010_ddd.to_csv("cm_2010_ddd.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2011_ddd.to_csv("cm_2011_ddd.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2012_ddd.to_csv("cm_2012_ddd.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2013_ddd.to_csv("cm_2013_ddd.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2014_ddd.to_csv("cm_2014_ddd.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2015_ddd.to_csv("cm_2015_ddd.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2016_ddd.to_csv("cm_2016_ddd.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2017_ddd.to_csv("cm_2017_ddd.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2018_ddd.to_csv("cm_2018_ddd.csv", sep=';', decimal = ",", encoding='utf-8')

In [44]:
#exportar como csv os dataframes com as análises de concentração de mercado
#análise de HHI por DDD
#df_2009_hhi_ddd.to_csv("hhi_2009_ddd.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2010_hhi_ddd.to_csv("hhi_2010_ddd.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2011_hhi_ddd.to_csv("hhi_2011_ddd.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2012_hhi_ddd.to_csv("hhi_2012_ddd.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2013_hhi_ddd.to_csv("hhi_2013_ddd.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2014_hhi_ddd.to_csv("hhi_2014_ddd.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2015_hhi_ddd.to_csv("hhi_2015_ddd.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2016_hhi_ddd.to_csv("hhi_2016_ddd.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2017_hhi_ddd.to_csv("hhi_2017_ddd.csv", sep=';', decimal = ",", encoding='utf-8')
#df_2018_hhi_ddd.to_csv("hhi_2018_ddd.csv", sep=';', decimal = ",", encoding='utf-8')