# Visualização de dados de 2009 a 2018

In [1]:
#importar as bibliotecas que serão 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#importar o arquivo com as tecnologias por mês de fev/2009 a 2018 em um dataframe
df_fev2009_2018_tec = pd.read_csv('./data/Acessos_Telefonia_Movel_200902-2018_Tecnologia_Colunas.csv', sep=';')

In [3]:
df_fev2009_2018_tec.head()

,CNPJ,Código Nacional,UF,Tecnologia,Tecnologia Geração,Empresa,Porte da Prestadora,Grupo Econômico,2009-02,2009-03,...,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12
0,40432544000147,11,SP,Dados,2G,CLARO,Grande Porte,TELECOM AMERICAS,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,40432544000147,11,SP,Dados > 256kbps,3G,CLARO,Grande Porte,TELECOM AMERICAS,NaN,146326.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,40432544000147,11,SP,Dados até 256kbps,2G,CLARO,Grande Porte,TELECOM AMERICAS,157408.0,20719.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,40432544000147,11,SP,Dados Banda Larga,3G,CLARO,Grande Porte,TELECOM AMERICAS,NaN,NaN,...,310659.0,307150.0,304434.0,299957.0,298277.0,295243.0,296820.0,295957.0,295539.0,292765.0
4,40432544000147,11,SP,GSM,2G,CLARO,Grande Porte,TELECOM AMERICAS,6090030.0,6077569.0,...,133574.0,120767.0,108000.0,103727.0,101157.0,101811.0,103618.0,98130.0,93625.0,84598.0

In [4]:
#alterar os NaN para zero, conforme decisão metodológico para cálculo da média do ano
df_fev2009_2018_tec = df_fev2009_2018_tec.fillna(0)

In [5]:
df_fev2009_2018_tec['media_ano_2009'] = round(df_fev2009_2018_tec[['2009-02','2009-03', '2009-04', '2009-05', '2009-06', '2009-07', '2009-08', '2009-09', '2009-10', '2009-11', '2009-12']].mean(axis=1), 2)
df_fev2009_2018_tec['media_ano_2010'] = round(df_fev2009_2018_tec[['2010-01', '2010-02', '2010-03', '2010-04', '2010-05', '2010-06', '2010-07', '2010-08', '2010-09', '2010-10', '2010-11', '2010-12']].mean(axis=1), 2)
df_fev2009_2018_tec['media_ano_2011'] = round(df_fev2009_2018_tec[['2011-01', '2011-02', '2011-03', '2011-04', '2011-05', '2011-06', '2011-07', '2011-08', '2011-09', '2011-10', '2011-11', '2011-12']].mean(axis=1), 2)
df_fev2009_2018_tec['media_ano_2012'] = round(df_fev2009_2018_tec[['2012-01', '2012-02', '2012-03', '2012-04', '2012-05', '2012-06', '2012-07', '2012-08', '2012-09', '2012-10', '2012-11', '2012-12']].mean(axis=1), 2)
df_fev2009_2018_tec['media_ano_2013'] = round(df_fev2009_2018_tec[['2013-01', '2013-02', '2013-03', '2013-04', '2013-05', '2013-06', '2013-07', '2013-08', '2013-09', '2013-10', '2013-11', '2013-12']].mean(axis=1), 2)
df_fev2009_2018_tec['media_ano_2014'] = round(df_fev2009_2018_tec[['2014-01', '2014-02', '2014-03', '2014-04', '2014-05', '2014-06', '2014-07', '2014-08', '2014-09', '2014-10', '2014-11', '2014-12']].mean(axis=1), 2)
df_fev2009_2018_tec['media_ano_2015'] = round(df_fev2009_2018_tec[['2015-01', '2015-02', '2015-03', '2015-04', '2015-05', '2015-06', '2015-07', '2015-08', '2015-09', '2015-10', '2015-11', '2015-12']].mean(axis=1), 2)
df_fev2009_2018_tec['media_ano_2016'] = round(df_fev2009_2018_tec[['2016-01', '2016-02', '2016-03', '2016-04', '2016-05', '2016-06', '2016-07', '2016-08', '2016-09', '2016-10', '2016-11', '2016-12']].mean(axis=1), 2)
df_fev2009_2018_tec['media_ano_2017'] = round(df_fev2009_2018_tec[['2017-01', '2017-02', '2017-03', '2017-04', '2017-05', '2017-06', '2017-07', '2017-08', '2017-09', '2017-10', '2017-11', '2017-12']].mean(axis=1), 2)
df_fev2009_2018_tec['media_ano_2018'] = round(df_fev2009_2018_tec[['2018-01', '2018-02', '2018-03', '2018-04', '2018-05', '2018-06', '2018-07', '2018-08', '2018-09', '2018-10', '2018-11', '2018-12']].mean(axis=1), 2)

In [6]:
df_fev2009_2018_tec['percentual_2009'] = ((df_fev2009_2018_tec['media_ano_2009'] / df_fev2009_2018_tec['media_ano_2009'].sum())) * 100 
df_fev2009_2018_tec['percentual_2010'] = ((df_fev2009_2018_tec['media_ano_2010'] / df_fev2009_2018_tec['media_ano_2010'].sum())) * 100
df_fev2009_2018_tec['percentual_2011'] = ((df_fev2009_2018_tec['media_ano_2011'] / df_fev2009_2018_tec['media_ano_2011'].sum())) * 100
df_fev2009_2018_tec['percentual_2012'] = ((df_fev2009_2018_tec['media_ano_2012'] / df_fev2009_2018_tec['media_ano_2012'].sum())) * 100
df_fev2009_2018_tec['percentual_2013'] = ((df_fev2009_2018_tec['media_ano_2013'] / df_fev2009_2018_tec['media_ano_2013'].sum())) * 100
df_fev2009_2018_tec['percentual_2014'] = ((df_fev2009_2018_tec['media_ano_2014'] / df_fev2009_2018_tec['media_ano_2014'].sum())) * 100
df_fev2009_2018_tec['percentual_2015'] = ((df_fev2009_2018_tec['media_ano_2015'] / df_fev2009_2018_tec['media_ano_2015'].sum())) * 100
df_fev2009_2018_tec['percentual_2016'] = ((df_fev2009_2018_tec['media_ano_2016'] / df_fev2009_2018_tec['media_ano_2016'].sum())) * 100
df_fev2009_2018_tec['percentual_2017'] = ((df_fev2009_2018_tec['media_ano_2017'] / df_fev2009_2018_tec['media_ano_2017'].sum())) * 100
df_fev2009_2018_tec['percentual_2018'] = ((df_fev2009_2018_tec['media_ano_2018'] / df_fev2009_2018_tec['media_ano_2018'].sum())) * 100

In [7]:
df_fev2009_2018_tec.head()

,CNPJ,Código Nacional,UF,Tecnologia,Tecnologia Geração,Empresa,Porte da Prestadora,Grupo Econômico,2009-02,2009-03,...,percentual_2009,percentual_2010,percentual_2011,percentual_2012,percentual_2013,percentual_2014,percentual_2015,percentual_2016,percentual_2017,percentual_2018
0,40432544000147,11,SP,Dados,2G,CLARO,Grande Porte,TELECOM AMERICAS,0.0,0.0,...,0.000000,0.000000,0.000000,0.040932,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,40432544000147,11,SP,Dados > 256kbps,3G,CLARO,Grande Porte,TELECOM AMERICAS,0.0,146326.0,...,0.097311,0.115007,0.099998,0.021518,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,40432544000147,11,SP,Dados até 256kbps,2G,CLARO,Grande Porte,TELECOM AMERICAS,157408.0,20719.0,...,0.022317,0.014579,0.015927,0.004202,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,40432544000147,11,SP,Dados Banda Larga,3G,CLARO,Grande Porte,TELECOM AMERICAS,0.0,0.0,...,0.000000,0.000000,0.000000,0.066351,0.123289,0.122139,0.148538,0.182783,0.155765,0.129530
4,40432544000147,11,SP,GSM,2G,CLARO,Grande Porte,TELECOM AMERICAS,6090030.0,6077569.0,...,3.787639,3.083385,2.357249,1.525084,0.938099,0.549291,0.295860,0.187279,0.098326,0.048299

In [8]:
df_fev2009_2018_tec.columns

Index(['CNPJ', 'Código Nacional', 'UF', 'Tecnologia', 'Tecnologia Geração',
       'Empresa', 'Porte da Prestadora', 'Grupo Econômico', '2009-02',
       '2009-03',
       ...
       'percentual_2009', 'percentual_2010', 'percentual_2011',
       'percentual_2012', 'percentual_2013', 'percentual_2014',
       'percentual_2015', 'percentual_2016', 'percentual_2017',
       'percentual_2018'],
      dtype='object', length=147)

In [16]:
df_grouped = pd.DataFrame(df_fev2009_2018_tec.groupby(['UF', 'Tecnologia Geração']))
df_grouped

             0                                                  1
0     (AC, 2G)                  CNPJ  Código Nacional  UF     ...
1     (AC, 3G)                  CNPJ  Código Nacional  UF     ...
2     (AC, 4G)                  CNPJ  Código Nacional  UF Tecn...
3    (AC, M2M)                  CNPJ  Código Nacional  UF    T...
4     (AL, 1G)                 CNPJ  Código Nacional  UF Tecno...
..         ...                                                ...
116  (SP, M2M)                  CNPJ  Código Nacional  UF    T...
117   (TO, 2G)                  CNPJ  Código Nacional  UF     ...
118   (TO, 3G)                  CNPJ  Código Nacional  UF     ...
119   (TO, 4G)                  CNPJ  Código Nacional  UF Tecn...
120  (TO, M2M)                  CNPJ  Código Nacional  UF    T...

[121 rows x 2 columns]

In [15]:
df_grouped_tec = pd.DataFrame(df_grouped.groupby('Tecnologia Geração'))
df_grouped_tec

KeyError: 'Tecnologia Geração'

In [10]:
g = sns.FacetGrid(df_2009_tec_uf_reset, col="UF")
g.map(sns.barplot, 'Tecnologia Geração', "percentual", order=["1G", "2G", "3G", "4G", "M2M"])

NameError: name 'df_2009_tec_uf_reset' is not defined